name: 欢乐战三国 签到

on:
  schedule:
    - cron: '30 0,10 * * *'
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/**'

env:
  TZ: Asia/Shanghai

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置Python环境至3.10.14
        uses: actions/setup-python@v3
        with:
          python-version: "3.10.14"

      - name: 创建并激活虚拟环境，安装依赖
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install playwright==1.45.1

      - name: 下载 chroemium
        run: |
          sudo wget http://www.linuxidc.com/files/repo/google-chrome.list -P /etc/apt/sources.list.d/
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub  | sudo apt-key add -
          sudo apt-get update
          sudo apt-get install google-chrome-stable
          echo /usr/bin/google-chrome-stable

      - name: 运行主程序
        env:
          APP_ID: ${{ secrets.APP_ID }}
          API_KEY: ${{ secrets.API_KEY }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
        run: |
          source venv/bin/activate
          python3 ./hlzsg/hlzsg.py
